//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechRepair.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientsOrder()
        {
            this.OrderMasterComment = new HashSet<OrderMasterComment>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<System.DateTime> CompliteDate { get; set; }
        public Nullable<int> MasterId { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual OrderStatusType OrderStatusType { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual TechModel TechModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMasterComment> OrderMasterComment { get; set; }
    }
}
