//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechRepair.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechRepairEntities : DbContext
    {
        public TechRepairEntities()
            : base("name=TechRepairEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientsOrder> ClientsOrder { get; set; }
        public virtual DbSet<OrderMasterComment> OrderMasterComment { get; set; }
        public virtual DbSet<OrderStatusType> OrderStatusType { get; set; }
        public virtual DbSet<SystemUser> SystemUser { get; set; }
        public virtual DbSet<Tech> Tech { get; set; }
        public virtual DbSet<TechModel> TechModel { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
